import 'package:guarda_sementes_front/src/models/semente_disponivel_troca_teste_model.dart';

class SementeDisponivelTrocaTesteRepository {
  static List<SementeDisponivelTrocaTesteModel> tabela = [
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 1,
      sdtBlDisponivel: true,
      semNrIdSemente: 1,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Feijão Vermelho',
      sdtNrQuantidade: 12,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 55.5,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 0.750,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 0.900,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 10,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 55.7,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 10,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 55.7,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 10,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 55.7,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 10,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 2,
      semTxNome: 'Feijão Preto Mocoto',
      sdtTxObservacoes: 'Trocar por Fava',
      sdtNrQuantidade: 55.7,
      icone: 'lib/assets/images/feijão-preto-mocoto.jpg',
    ),
    SementeDisponivelTrocaTesteModel(
      sdtNrId: 2,
      sdtBlDisponivel: true,
      semNrIdSemente: 3,
      semTxNome: 'Feijão Pombo',
      sdtTxObservacoes: 'Trocar por Milho Vermelho',
      sdtNrQuantidade: 10,
      icone: 'lib/assets/images/feijao-pombo.jpg',
    ),
  ];
}
